### ISSUE TITLE
Cache isn't cleared after player code is updated

### ISSUE THREAD

**Issue by dzaima** [davidje13/koth-webplayer#16]
After updating the player code from the "edit entries" button, the cache of the players actions doesn't seem to be cleared, resulting in weird results and making live editing often pretty much useless.

**Comment by davidje13** [comment]
I… er… oops! I wonder how much this mucked up my iterations of Wildfire back when I was working on it. Should be an easy fix I imagine; I'll take a look at the code a bit later.
