### ISSUE TITLE
Add team indicator for ants in zoomed view

### ISSUE THREAD

**Issue by davidje13** [davidje13/koth-webplayer#17]
Currently only the laden status of ants is represented in the zoomed view. It would be nice to see the team the ant belongs to somehow (coloured dot matching the team?), and might be useful to see which type (1/2/3/4) each worker is too.

Issue extracted from a note in https://github.com/GNiklasch/formic-windmill/issues/15 - thanks for the ping @GNiklasch

**Comment by Draco18s** [comment]
Agreed. Its one of the first things I added to my own controller fork.

**Comment by davidje13** [comment]
Team colours are shown in a small rectangle over the ant's icon. Also a tooltip has been added which shows the entry name, ant type, and current food.

6 new team colours have been added to keep up with the number of entries in this challenge (team colours are now duplicated in the CSS for the table view and the zoomed view, which isn't ideal; might be better to auto-generate these styles from a shared configuration instead).
